/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "Preliminary",
      items: [
        {
          type: "doc",
          id: "intro",
          label: "What is WoT",
        },
        {
          type: "doc",
          id: "payloads",
          label: "Payloads and Headers",
        },
        {
          type: "category",
          label: "JSON",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "json-tutorial/json1",
              label: "Introduction",
            },
            {
              type: "doc",
              id: "json-tutorial/json2",
              label: "JSON in Practice",
            },
          ],
        },
        {
          type: "category",
          label: "JSON Schema",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "json-tutorial/json3",
              label: "Introduction",
            },
            {
              type: "doc",
              id: "json-tutorial/json4",
              label: "JSON Schema in Practice",
            },
            {
              type: "doc",
              id: "json-tutorial/json5",
              label: "JSON Schema in Practice - Advanced Topics",
            },
            {
              type: "doc",
              id: "json-tutorial/json6",
              label: "JSON Schema Validation",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Advanced",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "osi-layers",
          label: "OSI Layers and Network Topologies",
        },
        {
          type: "doc",
          id: "application-domains",
          label: "Application Domains",
        },
        {
          type: "doc",
          id: "architecture-patterns",
          label: "Architecture Patterns",
        },
        {
          type: "doc",
          id: "building-blocks",
          label: "Building Blocks",
        },
      ],
    },
  ],
};

module.exports = sidebars;
