/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
    },
    {
      type: "category",
      label: "Preliminary",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "preliminary/payloads",
        },
        {
          type: "category",
          label: "JSON",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "preliminary/json/intro",
            },
            {
              type: "doc",
              id: "preliminary/json/practice",
            },
          ],
        },
        {
          type: "category",
          label: "JSON Schema",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "preliminary/json-schema/intro",
            },
            {
              type: "doc",
              id: "preliminary/json-schema/practice",
            },
            {
              type: "doc",
              id: "preliminary/json-schema/practice-advanced",
            },
            {
              type: "doc",
              id: "preliminary/json-schema/practice-validators",
            },
          ],
        },
        {
          type: "doc",
          id: "preliminary/osi-layers",
        },
      ],
    },

    {
      type: "category",
      label: "WoT",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "wot/building-blocks",
          label: "Building Blocks",
        },
        {
          type: "category",
          label: "Application Domains",
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "wot/application-domains/smart-home-and-cities",
              label: "Smart Home and Cities",
            },
            {
              type: "doc",
              id: "wot/application-domains/industrial-and-agriculture-systems",
              label: "Industrial and Agriculture Systems",
            }
          ],
        },
        {
          type: "category",
          label: "Thing Description",
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "wot/td/introduction",
              label: "Introduction",
            },
            {
              type: "doc",
              id: "wot/td/interaction-affordances",
              label: "Interaction Affordances",
            },

          ],
        }
        // {
        //   type: "doc",
        //   id: "wot/architecture-patterns",
        //   label: "Architecture Patterns",
        // },
      ],
    },
  ],
};

module.exports = sidebars;
