/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "What is WoT",
    },
    {
      type: "category",
      label: "Preliminary",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "preliminary/payloads",
          label: "Payloads and Headers",
        },
        {
          type: "category",
          label: "JSON",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "preliminary/json/intro",
              label: "Introduction to JSON",
            },
            {
              type: "doc",
              id: "preliminary/json/practice",
              label: "JSON in Practice",
            },
          ],
        },
        {
          type: "category",
          label: "JSON Schema",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "preliminary/json-schema/intro",
              label: "Introduction",
            },
            {
              type: "doc",
              id: "preliminary/json-schema/practice",
              label: "JSON Schema in Practice",
            },
            {
              type: "doc",
              id: "preliminary/json-schema/practice-advanced",
              label: "JSON Schema in Practice - Advanced Topics",
            },
            {
              type: "doc",
              id: "preliminary/json-schema/validators",
              label: "JSON Schema Validators",
            },
          ],
        },
        {
          type: "doc",
          id: "preliminary/osi-layers",
          label: "OSI Layers and Network Topologies",
        },
      ],
    },

    {
      type: "category",
      label: "WoT",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "wot/application-domains",
          label: "Application Domains",
        },
        {
          type: "doc",
          id: "wot/architecture-patterns",
          label: "Architecture Patterns",
        },
        {
          type: "doc",
          id: "wot/building-blocks",
          label: "Building Blocks",
        },
      ],
    },
  ],
};

module.exports = sidebars;
